BlogProj/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve
# importing views
from django.contrib.auth import views as auth_views
from blog import views as blogentry
from articles import views as blogarticle
from products import views as products
from comments.views import CommentView

from .views import autocomplete # haystack autocomplete view
from .forms import MySearchForm # haystack form
from haystack.views import SearchView # haystack generic searchview

urlpatterns = [ 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/', include('registration.backends.simple.urls',)),
    url(r'^allauth/', include('allauth.urls',)), #django registration
    # haystack search with custom form
    url(r'^search/?$', SearchView(form_class=MySearchForm), name='haystack_search'),
    url(r'^search/autocomplete/', autocomplete),
    # articles, products views
    url(r'^articles/', blogarticle.index),
    url(r'^products/', products.index),
	url(r'^entry/(?P<slug>[^\.]+)/',  # for single entry
    	blogentry.single_post, 
    	name='single_entry'),
    url(r'^article/(?P<slug>[^\.]+)/', # for single article 
    	blogarticle.single_post, 
    	name='single_article'),
    # comments class based view
    url(r'^add_comment/$', CommentView.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += url(r'^admin/', include('loginas.urls')),
urlpatterns += url(r'^media/(?P<path>.*)$', serve),
urlpatterns += url(r'^', blogentry.index), # MAIN PAGE - entries

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += url(r'^__debug__/', include(debug_toolbar.urls)),

products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):

	name = models.CharField(max_length=20)
	picture = models.ImageField(upload_to = 'pic_folder/', default = 'pic_folder/no-img.jpg')
	price = models.DecimalField(max_digits=6, decimal_places=2)

	def __str__(self):
		return '%s' % self.name

	def __unicode__(self):
		return '%s' % self.name

BlogProj/forms.py
from django import forms
from haystack.forms import SearchForm
from haystack.query import SearchQuerySet
class MySearchForm(SearchForm):
	def __init__(self, *args, **kwargs):
		super(MySearchForm, self).__init__(*args, **kwargs)
		self.fields['q'].widget.attrs.update({'class' : 'form-control'})
	
	#entry = forms.CharField(max_length=30)
	q = forms.CharField(required=False, label=('Search'))
	def search(self):
		if not self.is_valid():
			return self.no_query_found()

		if not self.cleaned_data.get('q'):
			return self.no_query_found()

		sqs = self.searchqueryset.auto_query(self.cleaned_data['q'])

		if self.load_all:
			sqs = sqs.load_all()

		return sqs

BlogProj/views.py
from django import views
from django.http import HttpResponse
from haystack.query import SearchQuerySet
import json
#     only one view here in root app, autocomplete for haystack

def autocomplete(request): # for haystack
	sqs = SearchQuerySet().autocomplete(body=request.GET.get('q','')[:10])
	suggestions = [result.title[:30].strip("[]") for result in sqs]
	# Make sure you return a JSON object, not a bare list.
	# Otherwise, you could be vulnerable to an XSS attack.
	the_data = json.dumps({'results': suggestions})
	return HttpResponse(the_data, content_type='application/json')

	def get_queryset(self):
		queryset = super(self).get_queryset()

products/views.py
from django.shortcuts import render_to_response, HttpResponse
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from BlogProj.tasks import send_confirmation_email
from .models import Product
import json
# Create your views here.

@method_decorator(csrf_exempt)
def index(request):
	if request.method == 'POST': # while we're submitting basket
		order = request.POST.get('order')
		price = request.POST.get('price')
		email = request.POST.get('email')
		if (email != ''): # if email is not empty
			text = "You've bought items:"+order+" , for "+price
			send_confirmation_email(text, email)
		return HttpResponse(
			json.dumps({"email": email}),
			content_type="application/json"
			)
	else:
		products=Product.objects.all()
		context = {
		"products": products,
		}
		template = "products.html"
		return render_to_response(template,context,context_instance=RequestContext(request))

BlogProj/templates/base.html
{% load compress %}
{% load staticfiles %}

<html>
<head>
	{% compress css %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" charset="utf-8">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css" charset="utf-8">
	<link rel="stylesheet" href="{% static 'css/blog-home.css' %}" type="text/css" charset="utf-8">
	<link rel="stylesheet" href="{% static 'css/align.css' %}" type='text/css' charset="utf-8">
	<script src="{% static 'js/tether.min.js' %}"></script>
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% endcompress %}
	<title>{% block head_title %}Demo DjangoBlog{% endblock %}</title>
	<style>
	.ac-results {
		margin-top: 4px;
	}
	.result-wrapper {
		padding: 0px;
	}
	.ac-result {
		padding: 5px;
		padding-left: 12px;
	}

	#form-div {
		background: black;
		position: fixed;
		bottom: 0px;
		right: 0px;
		z-index: 11;
		width: 420px;
	}
	#insider {
		margin-bottom: 10px;
		float: right;
		margin-right: 10px;
		z-index: 12;
		width: 400px;
	}
</style>

</head>
<body>
	
	<div id="form-div" class="collapse">
		<div id="insider">
			<form class="form-group my-2 my-lg-0 autocomplete-me" type="get" action="/search/">
				<div class="input-group m-t-s">
					<input autocomplete="off" class="form-control" type="text" placeholder="Search" id="id_q" name="q" autofocus>

					<span class="input-group-button">
						<button class="btn btn-success" type="submit">Search</button>
					</span>
				</div>

			</form>
		</div>
	</div>
	<nav class="navbar navbar-inverse fixed-top navbar-toggleable-md bg-inverse">
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="#">Demo DjangoBlog</a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">

				<li class="nav-item">
					<a {% if request.path == '/' %}
					class="nav-link active"
					{% else %}
					class="nav-link"
					{% endif %} href="/">Entries<span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a {% if request.path == '/articles/' %}
					class="nav-link active"
					{% else %}
					class="nav-link"
					{% endif %} href="/articles/">Articles</a>
				</li>
				<li class="nav-item">
					<a {% if request.path == '/products/' %}
					class="nav-link active"
					{% else %}
					class="nav-link"
					{% endif %} href="/products/">Products</a>
				</li>
				<li class="nav-item" style="width: 40px;">
				</li>
				{% if request.user.is_authenticated %}
				<li class="nav-item">
					<p class="text-success">Logged as {{ request.user.username }}</p>
				</li>
				<li class="nav-item">
					<a class="nav-link"  href="{% url 'auth_logout' %}?next=/"> Logout</a>
				</li>
				{% else %}
				
				<li class="nav-item">
					<a class="nav-link" href="/accounts/login/">Login</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/accounts/register/">Register</a>
				</li>
				{% endif %}

			</ul>
			<button id="search-button" class="btn btn-success my-2 my-sm-0" href="#toggleSearch" data-toggle="collapse" data-target="#form-div">Toggle search form!</button>
		</div>
	</nav>

	<script type="text/javascript">
    // cos for getting autocomplete suggestions
    
    var Autocomplete = function(options) {
    	this.form_selector = options.form_selector
    	this.url = options.url || '/search/autocomplete/'
    	this.delay = parseInt(options.delay || 300)
    	this.minimum_length = parseInt(options.minimum_length || 3)
    	this.form_elem = null
    	this.query_box = null
    }

    Autocomplete.prototype.setup = function() {
    	var self = this

    	this.form_elem = $(this.form_selector)
    	this.query_box = this.form_elem.find('input[name=q]')

      // Watch the input box.
      this.query_box.on('keyup', function() {
      	var query = self.query_box.val()

      	if(query.length < self.minimum_length) {
      		return false
      	}

      	self.fetch(query)
      })

      // On selecting a result, populate the search field.
      this.form_elem.on('click', '.ac-result', function(ev) {
      	self.query_box.val($(this).text())
      	$('.ac-results').remove()
      	return false
      })
  }

  Autocomplete.prototype.fetch = function(query) {
  	var self = this

  	$.ajax({
  		url: this.url
  		, data: {
  			'q': query
  		}
  		, success: function(data) {
  			self.show_results(data)
  		}
  	})
  }

  Autocomplete.prototype.show_results = function(data) {
      // Remove any existing results.
      $('.ac-results').remove()

      var results = data.results || []
      var results_wrapper = $('<ul class="list-group ac-results"></ul>')
      var base_elem = $('<li class="list-group-item result-wrapper"><a href="#" class="nav-link ac-result"></a></li>')

      if(results.length > 0) {
      	for(var res_offset in results) {
      		var elem = base_elem.clone()
          // Don't use .html(...) here, as you open yourself to XSS.
          // Really, you should use some form of templating.
          elem.find('.ac-result').text(results[res_offset])
          results_wrapper.append(elem)
      }
  }
  else {
  	var elem = base_elem.clone()
  	elem.text("No results found.")
  	results_wrapper.append(elem)
  }

  this.query_box.parent().after(results_wrapper)
}

$(document).ready(function() {
	window.autocomplete = new Autocomplete({
		form_selector: '.autocomplete-me'
	})
	window.autocomplete.setup()
})
</script>
<div style="height: 7%;"></div>
{% block content %}

{% endblock %}
</body>
</html>

BlogProj/templates/comment_result.html
{% extends 'base.html' %}

{% block content %}
<!-- Page Content -->
<div class="container">
	{% if valid %}
	<h1 class="my-4">Success my dear user<hr>
		<small>Comment added successfully</small>
		

	</h1>
	{% else %}
	<h1 class="my-4">Error my dear user<hr>
		<small>Comment cannot be empty or longer than 120 signs</small>

	</h1>
	{% endif %}
</div>


{% endblock %}

BlogProj/templates/entry.html
{% extends 'base.html' %}
{% block title %}Welcome to da Blogg!{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">
  <h1 class="my-4">Displaying single {{ type }}
    <small>right now</small>
  </h1>
  <div class="row">
    {% if post %}

    <div class="col-md-12">
      <div class="card mb-4">
        <div class="card-body m-t-s" style="padding-left: 15px; padding-right: 15px;">
          <h2 class="card-title">{{ post.title }}</h2>
          <hr>
          <p class="card-text">{{ post.body }}</p>
          <hr>
          <div class="btn-group m-b-s">
            <a class="btn btn-primary" href="/">Go to main page</a>

            <a class="btn btn-success green" data-toggle="collapse" href="#comments" aria-expanded="false" aria-controls="comments">
              Show da comments
            </a>

          </div>
        </div>
        <div class="collapse" id="comments">
          <div class="card card-block">
            <form class="form-group" method='POST' action='/add_comment/'> 
              {% csrf_token %}
              <input type='hidden' value='{{ post.id }}' name='id'>
              {% if request.user.is_authenticated %}
              <input type='hidden' value='{{ request.user.username }}' name='user'>

              {% else %}
              <input type='hidden' value='guest' name='user'>

              {% endif %}
              <input type='hidden' value='{{ type }}' name='type'>

              <textarea class="form-control" name="body" placeholder="Do you want to comment this?" ></textarea>

              <button type="submit" class="btn btn-success green form-control"> Add comment</button>
            </form>
            <ul class="list-group list-group-flush">
              {% if post.comments %}
              {% for comment in post.comments.all|dictsortreversed:"id" %}
              <li class="list-group-item">
                {{ comment.body }}
                <a style="margin-left: 10%; color: green;"> <!-- not really important for now -->
                  ~{{ comment.user }}
                </a></li>
                {% endfor %}
                {% else %}
                <li class="list-group-item">No comments for now</li>

                {% endif %}
              </ul>
            <!-- below were submitting comment by POST together with post.id -->      

          </div>

        </div>
        <div class="card-footer text-muted">
          Created: {{ post.created }}
        </div>
        
      </div>
    </div>

    {% endif %}

  </div>

</div>


{% endblock %}

BlogProj/templates/entry_list.html
{% extends 'base.html' %}
{% block title %}Welcome to da Blogg!{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">
  {{ form }}
  <h1 class="my-4">
    {% if type == 'entry' %}
    My blog entries
    <small>, powered by dżango</small>

    {% else %}
    My blog articles
    <small>, powered by dżango</small>
    {% endif %}
  </h1>
  <div class="row">
    {% if posts %}
    {% for post in posts %}

    <div class="col-md-12">
      <div class="card mb-4">
        <div class="card-body m-t-s" style="padding-left: 15px; padding-right: 15px;">
          <h2 class="card-title">{{ post.title }}</h2>
          <hr>
          <p class="card-text">{{ post.body }}</p>
          <hr>
          <div class="btn-group m-b-s">
            <a class="btn btn-primary" href="{{ post.get_absolute_url }}">Show me whole entry</a>

            <a class="btn btn-success green" data-toggle="collapse" href="#comments{{ post.id }}" aria-expanded="false" aria-controls="comments{{ post.id }}">
              Show da comments
            </a>

          </div>
        </div>
        <div class="collapse" id="comments{{ post.id }}">
          <div class="card card-block">
            <form class="form-group" method='POST' action='/add_comment/'> 
              {% csrf_token %}
              <input type='hidden' value='{{ post.id }}' name='id'>
              {% if request.user.is_authenticated %}
              <input type='hidden' value='{{ request.user.username }}' name='user'>

              {% else %}
              <input type='hidden' value='guest' name='user'>

              {% endif %}
              <input type='hidden' value='{{ type }}' name='type'>

              <textarea class="form-control" name="body" placeholder="Do you want to comment this?" ></textarea>

              <button type="submit" class="btn btn-success green form-control"> Add comment</button>
            </form>
            <ul class="list-group list-group-flush">
              {% if post.comments %}
              {% for comment in post.comments.all|dictsortreversed:"id" %}
              <li class="list-group-item">
                {{ comment.body }}
                <a style="margin-left: 10%; color: green;"> <!-- not really important for now -->
                  ~{{ comment.user }}
                </a></li>
                {% endfor %}
                {% else %}
                <li class="list-group-item">No comments for now</li>

                {% endif %}
              </ul>
              <!-- below were submitting comment by POST together with post.id -->      
            </div>

          </div>
          <div class="card-footer text-muted">
            Created: {{ post.created }} , comments count: {{ post.comments_count }}
          </div>
        </div>
      </div>


      {% endfor %}

      {% else %}
      <p>There are no posts.</p>
      {% endif %}
      <!-- Sidebar Widgets Column -->
<!--   <div class="col-md-4">
    some potential widget here
  </div> -->
</div>
</div>
</div>

</div>

{% endblock %}

BlogProj/templates/products.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="container col-12 m-t-l" style="margin-left: 30px;">
	
	<div class="row">
		{% for product in products %}

		<div class="card text-center" style="width: 20rem; display: inline-block;">
			<img class="card-img-top img-thumbnail m-t-s" style="width: 150px; height: 150px;" src="{{ product.picture.url }}" alt="product image">
			<div class="card-block">
				<h4 class="card-title" style="color: black;">{{ product.name }}</h4>

				<p class="card-text text-success m-t-m">
					<i class="remove fa fa-minus" style="cursor: pointer" aria-hidden="true"></i>

					{{ product.price }}
					
					<i class="add fa fa-plus" style="cursor: pointer" aria-hidden="true"></i>

				</p>
				
				
			</div>
		</div>
		{% empty %}
		<p class="text-faded">No products here</p>
		{% endfor %}

	</div>
	<div class="col-lg-5 col-md-5 col-sm-6 text-center m-t-l" style="position: fixed; bottom: 10px; right: 10px;">
		<div class="card m-b-s" style="padding: 10px;">
			<h2 class="">Your basket:</h2>
			<ul class="text-danger list-group" id="order">add a product</ul>
			<p class="text-success m-t-s" id="price">---</p>
			<form id="buy-form">
				<button id="buy" class="btn btn-success green m-b-s">Buy this crap</button>
			</form>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() { // i will keep products and counters in two arrays
		var totalPrice = 0;
		var products = [];
		var productsCounter = [];
		$('.add').on('click', add); // attaching click to buttons
		$('.remove').on('click', remove);
		function add(e) {
			var price = parseFloat($(e.target).parent().text());
			totalPrice += price; // counting price

			var product = $(e.target).parent().parent().children().eq(0).html();
			var existsInArray = jQuery.inArray(product, products);
			if (existsInArray == -1) { // no product in array
				products.push(product);
				productsCounter.push(1);
			} else {
				productsCounter[existsInArray]++;
			}
			
			var order = "";
			for (var item in products) {
				order += "<li class='list-group-item'>"+products[item]+" x"+productsCounter[item]+"</li>";
			}
			
			$("#order").html(order);
			$("#price").text(totalPrice.toFixed(2)+"zł");
		} 
		function remove(e) {
			var price = parseFloat($(e.target).parent().text());
			var product = $(e.target).parent().parent().children().eq(0).html();
			var existsInArray = jQuery.inArray(product, products);
			if (existsInArray == -1) { // no product in array
				console.log('nothing in products');
				return; // nothing to remove so returning
			} else {
				console.log('remove from products');
				productsCounter[existsInArray]--;
				var i = productsCounter[existsInArray];
				if (i == 0) {
					var index = products.indexOf(product);
					if (index > -1) {
						productsCounter.splice(index, 1); //resetting counter also
					}
					products = jQuery.grep(products, function(value) { // delete product from array
						return value != product;
					});
				}
				totalPrice -= price;
				var order = "";
				for (var item in products) {
					order += "<li class='list-group-item'>"+products[item]+" x"+productsCounter[item]+"</li>";
				}

				$("#order").html(order);
				$("#price").text(totalPrice.toFixed(2)+"zł");
			}
		}
		$('#buy-form').on('click', function(e) {
			e.preventDefault();
			totalPrice = 0; //  resetting basket items and price
			products = [];
			productsCounter = [];
			order = '';
			//$('.add').off('click'); // disabling buttons while waiting 
			SubmitBasket();
		});
		
		function SubmitBasket() {
			$.ajax({
		type : "POST", 
        url : "submit_basket/", 
        data : { order : $('#order').text(), price: $('#price').text(), email : "{{ request.user.email }}" }, // data sent with the post request

        // handle a successful response
        success : function(json) {

        	$('#order').text('');
        	if (json.email == '') { // if user has no email
        		$('#price').text('Please create account with email'); 
        	} else {
        		$('#price').text('Confirmation sent: '+json.email); 
        		$('#buy').hide();
        	}
            //console.log(json.email); 
            console.log("success"); // sanity check
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
        	$('#order').text('');
        	$('#price').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error!</div>"); // add the error to the dom
            //console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
		};
	});

</script>

{% endblock %}